# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3884f20af7e889c5777588c8b562c8170e1dfffafe3d5c1c5756a404c81e34ee0085dbbb4e11001f3403bc7941d330d4a142d662261d7a0b2cf65a1522615bd2

test:
  secret_key_base: 3ba9e3bd7f5989f4846e48e7e37482c702f7d53b34062056406788394656f00aea3d5d00dde487d2c13ca48f47e6ac2e502b9ed246e33608b2ae83303e7aac50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
